name: Acceptance Stage

on:
  repository_dispatch:
    types: [fresh-artifact]
  schedule:
    - cron: "0 * * * 1-5"
  workflow_dispatch:
    inputs:
      run_id:
        description: "The id of the workflow run where the desired download artifact was uploaded from."
        required: false
        type: number

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_new_commits:
    name: Check if the app repo has new commits
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check for new commits
        id: check_commits
        run: |
          NEW_COMMITS=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository_owner }}/my-electron-app/commits?since=$(date -u -d '1 hour ago' '+%Y-%m-%dT%H:%M:%SZ'))
          if [ $(echo $NEW_COMMITS | jq length) -gt 0 ]; then
            echo "New commits found"
            echo "has_new_commits=true" >> $GITHUB_OUTPUT
          else
            echo "No new commits found"
            echo "has_new_commits=false" >> $GITHUB_OUTPUT
          fi

      - name: Cancel workflow if no new commits
        if: ${{ steps.check_commits.outputs.has_new_commits == 'false' && github.event_name == 'schedule' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository_owner }}/electron-app-tests/actions/runs/${{ github.run_id }}/cancel

  fetch_run_id:
    name: Get Last Workflow Run ID
    runs-on: ubuntu-latest
    needs: [check_new_commits]
    outputs:
      run_id: ${{ steps.run_id.outputs.run_id }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Fetching last workflow Run ID
        id: run_id
        run: |
          is_valid_input=${{ github.event.client_payload.run_id || github.event.inputs.run_id }}
          if [[ -n "$is_valid_input" ]]; then
            run_id=$is_valid_input
          else
            response=$(gh api /repos/${{github.repository_owner}}/my-electron-app/actions/workflows/nightlyBuild.yml/runs?status=success&per_page=1)
            run_id=$(echo "$response" | jq -r '.workflow_runs[0].id | tonumber')
          fi
          echo "run_id=$run_id" >> $GITHUB_OUTPUT

  cache-artifact:
    name: Cache Artifact
    runs-on: macos-latest
    needs: fetch_run_id
    steps:
      - name: Trying restore artifact cache
        uses: actions/cache/restore@v4
        id: cache-artifact-restore
        with:
          path: ./MongoDB Query Executor
          key: ${{ runner.os }}-cache-artifact-${{needs.fetch_run_id.outputs.run_id}}
      - name: Download Artifacts
        if: steps.cache-artifact-restore.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{github.repository_owner}}/my-electron-app
          run-id: ${{needs.fetch_run_id.outputs.run_id}}
      - name: Save Cache
        id: cache-artifact-save
        if: steps.cache-artifact-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ./MongoDB Query Executor
          key: ${{ runner.os }}-cache-artifact-${{needs.fetch_run_id.outputs.run_id}}

  acceptance_env:
    name: Deploying artifacts to Acceptance Environment and run tests
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWMER: ${{ github.repository_owner }}
      VITE_VERSION_API: http://localhost:8080/api/check-version
      ACP_ENV: true
    needs: [fetch_run_id, cache-artifact]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore artifacts and common test steps
        uses: ./.github/actions/restore-common_tests
        with:
          run_id: ${{ needs.fetch_run_id.outputs.run_id }}
          node-version: 20

      - name: Run Acceptance Test Theme Stubbing script that sets a theme env var
        run: ./automated_testing/prepare-for-acceptance-tests.sh

      - name: Run Acceptance Tests
        run: npm run test:acceptance

      - name: Rub External system contract tests against stubs
        run: npm run test:externalStubs

      - name: Stop Mock services
        run: ./automated_testing/mock-end.sh

  e2e_env:
    name: Deploying artifacts to E2E Environment and run tests
    env:
      VITE_VERSION_API: localhost:8080/api/check-version
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWMER: ${{ github.repository_owner }}
      E2E_ENV: true
    runs-on: macos-latest
    needs: [fetch_run_id, cache-artifact]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore artifacts and common test steps
        uses: ./.github/actions/restore-common_tests
        with:
          run_id: ${{ needs.fetch_run_id.outputs.run_id }}
          node-version: 20

      - name: Run External System Contract Tests against Real
        run: npm run test:externalReal

      - name: Run E2E Tests
        run: npm run test:e2e

      - name: Stop Mock services
        run: ./automated_testing/mock-end.sh

  upload_artifact:
    name: Upload Artifact
    runs-on: macos-latest
    needs: [acceptance_env, e2e_env, fetch_run_id]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Artifacts
        uses: ./.github/actions/restore-artifacts
        with:
          run_id: ${{ needs.fetch_run_id.outputs.run_id }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 5
          name: MongoDB Query Executor
          path: ./MongoDB Query Executor/**/*.dmg
          if-no-files-found: "error"

  acceptance_stage_badge:
    name: Create status badge for workflow
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [acceptance_env, e2e_env]
    steps:
      - name: E2E Environment badge (Success)
        if: ${{ !contains(needs.*.result, 'failure') }}
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: acceptance_stage
          LABEL: "Acceptance Stage"
          STATUS: "Success"
          COLOR: green
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: E2E Environment badge (Failure)
        if: ${{ contains(needs.*.result, 'failure') }}
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: acceptance_stage
          LABEL: "Acceptance Stage"
          STATUS: "Failure"
          COLOR: red
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
